-- ============================================================
-- GOOD: Compliant SQL (should pass all rules)
-- ============================================================

CREATE TABLE IF NOT EXISTS IOTI_RAW_TB_SENSOR_READINGS (
    SENSOR_ID NUMBER(10) NOT NULL,
    READING_VALUE NUMBER(18,6),
    READING_TS TIMESTAMP_TZ,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw sensor readings from IoT devices';

CREATE OR REPLACE VIEW IOTI_RAW_VW_SENSOR_LATEST AS
SELECT
    SENSOR_ID,
    READING_VALUE,
    READING_TS
FROM IOTI_RAW_TB_SENSOR_READINGS
WHERE READING_TS >= DATEADD('day', -1, CURRENT_TIMESTAMP());

CREATE SCHEMA IF NOT EXISTS RAW_V001;

CREATE OR REPLACE DYNAMIC TABLE IOTI_RAW_DT_SENSOR_HOURLY
    TARGET_LAG = '60 MINUTE'
    WAREHOUSE = MD_TEST_WH
AS
SELECT
    SENSOR_ID,
    DATE_TRUNC('hour', READING_TS) AS HOUR_TS,
    AVG(READING_VALUE) AS AVG_VALUE,
    COUNT(*) AS CNT
FROM IOTI_RAW_TB_SENSOR_READINGS
GROUP BY SENSOR_ID, DATE_TRUNC('hour', READING_TS);

CREATE STAGE IF NOT EXISTS IOTI_RAW_ST_INBOUND;

CREATE OR REPLACE FILE FORMAT IOTI_RAW_FF_CSV
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

DROP TABLE IF EXISTS IOTI_RAW_TB_OLD_DATA;

COPY INTO IOTI_RAW_TB_SENSOR_READINGS
FROM @IOTI_RAW_ST_INBOUND
FILE_FORMAT = IOTI_RAW_FF_CSV
ON_ERROR = 'CONTINUE';
